//! Golden-vector conformance harness: replays every scenario in
//! `../testdata/golden.json` (generated by the Go reference) against a fresh
//! zeroed `MemStore`, asserting every op's `expect` kind, every check, and
//! finally the SHA-256 of the entire drive image.
//!
//! SHA-256 comes from the RustCrypto `sha2` crate (the de-facto standard);
//! the golden file is parsed untyped with `serde_json`.

use cartesi_accounts_drive::{Balance, Config, Drive, Error, MemStore};
use serde_json::Value;
use sha2::{Digest, Sha256};
use std::path::Path;

// --------------------------------------------------------------- the harness

/// Untyped field accessors over a `serde_json::Value` object, defaulting on
/// absent fields exactly like the harness always has.
trait Fields {
    fn str(&self, key: &str) -> &str;
    fn u64(&self, key: &str) -> u64;
    fn bool(&self, key: &str) -> bool;
    fn arr(&self, key: &str) -> &[Value];
}

impl Fields for Value {
    fn str(&self, key: &str) -> &str {
        self.get(key).and_then(Value::as_str).unwrap_or("")
    }
    fn u64(&self, key: &str) -> u64 {
        self.get(key).and_then(Value::as_u64).unwrap_or(0)
    }
    fn bool(&self, key: &str) -> bool {
        self.get(key).and_then(Value::as_bool).unwrap_or(false)
    }
    fn arr(&self, key: &str) -> &[Value] {
        self.get(key).and_then(Value::as_array).map_or(&[], Vec::as_slice)
    }
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn unhex(s: &str) -> Vec<u8> {
    assert!(s.len() % 2 == 0, "odd hex string {s:?}");
    (0..s.len() / 2)
        .map(|i| u8::from_str_radix(&s[2 * i..2 * i + 2], 16).expect("bad hex"))
        .collect()
}

fn to_addr(s: &str) -> [u8; 20] {
    let b = unhex(s);
    let mut a = [0u8; 20];
    a[..b.len().min(20)].copy_from_slice(&b[..b.len().min(20)]);
    a
}

fn to_balance(s: &str) -> Balance {
    let mut v = [0u8; 32];
    if !s.is_empty() {
        let b = unhex(s);
        assert_eq!(b.len(), 32, "value must be 32 bytes: {s:?}");
        v.copy_from_slice(&b);
    }
    v
}

/// Maps an op outcome to the golden `expect` kind, mirroring the Go
/// reference's kindOf.
fn kind_of(res: &Result<(), Error>) -> String {
    match res {
        Ok(()) => "ok".into(),
        Err(Error::TableFull) => "tableFull".into(),
        Err(Error::RegistryFull) => "registryFull".into(),
        Err(Error::Overflow) => "overflow".into(),
        Err(Error::NonceProtected) => "nonceProtected".into(),
        Err(Error::DuplicateToken) => "duplicateToken".into(),
        Err(Error::UnknownToken) => "unknownToken".into(),
        Err(Error::BadWidth) => "badWidth".into(),
        Err(Error::ZeroAddress) => "zeroAddress".into(),
        Err(Error::Profile) => "profile".into(),
        Err(e) => format!("error: {e}"),
    }
}

fn replay(sc: &Value) {
    let name = sc.str("name");
    let c = sc.get("config").expect("scenario config");
    let mut cfg = Config {
        drive_length: c.u64("driveLength"),
        capacity: c.u64("capacity"),
        load_limit: c.u64("loadLimit"),
        profile: c.u64("profile") as u32,
        slot_size: c.u64("slotSize") as u32,
        table_offset: c.u64("tableOffset"),
        registry_offset: c.u64("registryOffset"),
        registry_capacity: c.u64("registryCapacity"),
        sparse_offset: c.u64("sparseOffset"),
        sparse_capacity: c.u64("sparseCapacity"),
        sparse_load_limit: c.u64("sparseLoadLimit"),
        sparse_slot_size: c.u64("sparseSlotSize") as u32,
        ..Config::default()
    };
    let seed = unhex(c.str("seed"));
    cfg.seed.copy_from_slice(&seed);

    let store = MemStore::new(cfg.drive_length);
    let mut d = Drive::format(store, cfg)
        .unwrap_or_else(|e| panic!("{name}: format: {e}"));

    for (i, op) in sc.arr("ops").iter().enumerate() {
        let kind = op.str("op");
        let res: Result<(), Error> = match kind {
            "setAccount" => d.set_account(
                &to_addr(op.str("addr")),
                op.u64("nonce"),
                &to_balance(op.str("value")),
            ),
            "deleteAccount" => d
                .delete_account(&to_addr(op.str("addr")), op.bool("force"))
                .map(|_| ()),
            "registerToken" => d
                .register_token(&to_addr(op.str("token")), op.u64("width") as u32)
                .map(|_| ()),
            "setTokenBalance" => d.set_token_balance(
                &to_addr(op.str("addr")),
                op.u64("id") as u16,
                &to_balance(op.str("value")),
            ),
            other => panic!("{name} op {i}: unknown op {other:?}"),
        };
        let got = kind_of(&res);
        let want = op.str("expect");
        assert_eq!(got, want, "{name} op {i} ({kind}): outcome");
    }

    for (i, chk) in sc.arr("checks").iter().enumerate() {
        match chk.str("check") {
            "account" => {
                let addr = chk.str("addr");
                let got = d
                    .get_account(&to_addr(addr))
                    .unwrap_or_else(|e| panic!("{name} check {i}: {e}"));
                let want_found = chk.bool("found");
                match got {
                    None => assert!(!want_found, "{name} check {i}: {addr} not found"),
                    Some(a) => {
                        assert!(want_found, "{name} check {i}: {addr} unexpectedly found");
                        assert_eq!(a.nonce, chk.u64("nonce"), "{name} check {i}: nonce");
                        assert_eq!(
                            hex(&a.balance),
                            chk.str("value"),
                            "{name} check {i}: balance"
                        );
                    }
                }
            }
            "tokenBalance" => {
                let v = d
                    .get_token_balance(&to_addr(chk.str("addr")), chk.u64("id") as u16)
                    .unwrap_or_else(|e| panic!("{name} check {i}: {e}"));
                assert_eq!(hex(&v), chk.str("value"), "{name} check {i}: token balance");
            }
            "liveCount" => {
                let n = if chk.str("table") == "sparse" {
                    d.sparse_live_count()
                } else {
                    d.live_count()
                }
                .unwrap();
                assert_eq!(n, chk.u64("count"), "{name} check {i}: liveCount");
            }
            "slot" => {
                let idx = chk.u64("index");
                let slot = if chk.str("table") == "sparse" {
                    d.sparse_slot(idx)
                } else {
                    d.account_slot(idx)
                }
                .unwrap_or_else(|e| panic!("{name} check {i}: {e}"));
                assert_eq!(hex(&slot), chk.str("hex"), "{name} check {i}: slot {idx}");
            }
            other => panic!("{name} check {i}: unknown check {other:?}"),
        }
    }

    let sum: [u8; 32] = Sha256::digest(d.store().bytes()).into();
    assert_eq!(hex(&sum), sc.str("sha256"), "{name}: drive image sha256");
}

#[test]
fn golden() {
    // Resolve the vectors relative to this crate, so tests run from anywhere.
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../testdata/golden.json");
    let data = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let root: Value =
        serde_json::from_str(&data).unwrap_or_else(|e| panic!("parse golden.json: {e}"));
    let scenarios = root.arr("scenarios");
    assert!(!scenarios.is_empty(), "golden file has no scenarios");
    for sc in scenarios {
        replay(sc);
        println!("scenario {:?}: ok", sc.str("name"));
    }
}
