// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.22;

import {Test} from "forge-std/Test.sol";

import {Encoding} from "../src/vendor/optimism/Encoding.sol";
import {Hashing} from "../src/vendor/optimism/Hashing.sol";
import {Types} from "../src/vendor/optimism/Types.sol";
import {Vectors} from "./Vectors.sol";

/// @notice Pins the guest's cross-domain message encodings (@op-cartesi/evm
/// crossdomain.ts) to the OP Stack's own Encoding and Hashing libraries,
/// vendored verbatim. From the moment a withdrawal carries a relayMessage
/// payload these encodings are consensus the guest must reproduce exactly:
/// L1CrossDomainMessenger recomputes the v1 hash for replay protection, and
/// the withdrawal hash is what the portal proves.
///
/// The withdrawal half comes from the shared vectors
/// (`conformance/encodings/withdrawal.json`, case `messenger`): the relay
/// payload the guest emits, the gas limit it chose, and the hash the portal
/// will key by. The v1 message hash below is still a pasted constant, because
/// the reference for the messenger encodings is the *guest*, so their vector
/// would have to be generated by the TypeScript side — the one set
/// `conformance/README.md` lists as still missing.
contract CrossDomainVectorsTest is Test {
    address constant L2_MESSENGER = 0x4200000000000000000000000000000000000007;
    address constant L2_BRIDGE = 0x4200000000000000000000000000000000000010;
    address constant L1_MESSENGER = 0x00000000000000000000000000000000000f00F7;
    address constant L1_BRIDGE = 0x00000000000000000000000000000000000F0010;

    // finalizeBridgeERC20(l1Token, l2Token, from, to, 300, "") — the inner
    // message the L2 bridge sends for a 300-unit withdrawal.
    bytes constant MESSAGE =
        hex"0166a07a00000000000000000000000059b670e9fa9d0a427751af201d676719a970857b000000000000000000000000e78a0f7e598cc8b0bb87894b0f60dd2a88d6a8ab000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb9226600000000000000000000000000000000000000000000000000000000000000bb000000000000000000000000000000000000000000000000000000000000012c00000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000000";

    // encodeRelayMessage of the message above: messenger nonce 0 version 1,
    // sender = L2 bridge, target = L1 bridge, value 0, minGasLimit 200000.
    // The bytes are the messenger withdrawal's data in the vectors, so this
    // test and the node judge the same payload.
    uint256 constant MESSENGER = 3;
    string constant MESSENGER_ID = "messenger";

    bytes32 constant MSG_HASH = 0xc1809ec84428317a8537ac71ae4c83f6037ea1e7fe63911248b984dabd571e88;

    function messageNonce() internal pure returns (uint256) {
        return Encoding.encodeVersionedNonce(0, 1);
    }

    /// The guest's relayMessage bytes are Encoding.encodeCrossDomainMessageV1.
    function testRelayMessageEncodingMatches() public view {
        bytes memory encoded = Encoding.encodeCrossDomainMessageV1(
            messageNonce(), L2_BRIDGE, L1_BRIDGE, 0, 200_000, MESSAGE
        );
        assertEq(
            encoded,
            Vectors.withdrawal(MESSENGER, MESSENGER_ID).data,
            "relayMessage encoding drifted"
        );
    }

    /// The replay-protection hash both messengers key by.
    function testCrossDomainMessageHashMatches() public pure {
        bytes32 hash = Hashing.hashCrossDomainMessageV1(
            messageNonce(), L2_BRIDGE, L1_BRIDGE, 0, 200_000, MESSAGE
        );
        assertEq(hash, MSG_HASH, "hashCrossDomainMessageV1 drifted");
    }

    /// The withdrawal hash the portal proves for the wrapped message. Every
    /// field is the vector's, so this checks the guest's withdrawal against
    /// OP's own hashing rather than against a number copied out of a Go run.
    function testMessengerWithdrawalHashMatches() public view {
        Vectors.Withdrawal memory w = Vectors.withdrawal(MESSENGER, MESSENGER_ID);
        assertEq(w.sender, L2_MESSENGER, "sender");
        assertEq(w.target, L1_MESSENGER, "target");
        assertEq(w.nonce, Encoding.encodeVersionedNonce(uint240(42) << 32, 1), "versioned nonce");
        // The guest's baseGas(len(MESSAGE), 200000). Not recomputed on L1 —
        // only its place inside the withdrawal hash matters — but asserted
        // here so a formula change is a visible decision.
        assertEq(w.gasLimit, 516_982, "baseGas");

        bytes32 hash = Hashing.hashWithdrawal(
            Types.WithdrawalTransaction({
                nonce: w.nonce,
                sender: w.sender,
                target: w.target,
                value: w.value,
                gasLimit: w.gasLimit,
                data: w.data
            })
        );
        assertEq(hash, w.hash, "the messenger-shaped withdrawal hash drifted");
    }
}
