#!/usr/bin/env python3
"""Convert the cross-language golden vectors (testdata/golden.json) into a
generated C header of scenario arrays, so the C test binary can replay them
without a JSON parser. Stdlib only; run by the Makefile at build time.

Usage: gen_golden.py <golden.json> <out.h>
"""
import json
import sys

EXPECT = {
    "ok": "ACCTDRV_OK",
    "tableFull": "ACCTDRV_ERR_TABLE_FULL",
    "registryFull": "ACCTDRV_ERR_REGISTRY_FULL",
    "overflow": "ACCTDRV_ERR_OVERFLOW",
    "nonceProtected": "ACCTDRV_ERR_NONCE_PROTECTED",
    "duplicateToken": "ACCTDRV_ERR_DUPLICATE_TOKEN",
    "unknownToken": "ACCTDRV_ERR_UNKNOWN_TOKEN",
    "badWidth": "ACCTDRV_ERR_BAD_WIDTH",
    "zeroAddress": "ACCTDRV_ERR_ZERO_ADDRESS",
    "profile": "ACCTDRV_ERR_PROFILE",
}

OPS = {
    "setAccount": "GOP_SET_ACCOUNT",
    "deleteAccount": "GOP_DELETE_ACCOUNT",
    "registerToken": "GOP_REGISTER_TOKEN",
    "setTokenBalance": "GOP_SET_TOKEN_BALANCE",
}

CHECKS = {
    "account": "GCHK_ACCOUNT",
    "tokenBalance": "GCHK_TOKEN_BALANCE",
    "liveCount": "GCHK_LIVE_COUNT",
    "slot": "GCHK_SLOT",
}


def hexbytes(s, size, what):
    """Decode a hex string; an absent/empty field means `size` zero bytes."""
    b = bytes.fromhex(s or "")
    if not b:
        b = bytes(size)
    if len(b) != size:
        sys.exit(f"gen_golden.py: {what}: got {len(b)} bytes, want {size}")
    return b


def carr(b):
    return "{" + ",".join(f"0x{x:02x}" for x in b) + "}"


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_golden.py <golden.json> <out.h>")
    with open(sys.argv[1]) as f:
        golden = json.load(f)
    scenarios = golden["scenarios"]
    if not scenarios:
        sys.exit("gen_golden.py: golden file has no scenarios")

    out = []
    w = out.append
    w("/* Generated by test/gen_golden.py from testdata/golden.json.")
    w(" * Do not edit; regenerate via make. */")
    w("#ifndef GOLDEN_VECTORS_H")
    w("#define GOLDEN_VECTORS_H")
    w("")
    w('#include "accounts_drive.h"')
    w("")
    w("#include <stddef.h>")
    w("#include <stdint.h>")
    w("")
    w("typedef enum {")
    w("    GOP_SET_ACCOUNT,")
    w("    GOP_DELETE_ACCOUNT,")
    w("    GOP_REGISTER_TOKEN,")
    w("    GOP_SET_TOKEN_BALANCE")
    w("} golden_op_kind;")
    w("")
    w("typedef enum {")
    w("    GCHK_ACCOUNT,")
    w("    GCHK_TOKEN_BALANCE,")
    w("    GCHK_LIVE_COUNT,")
    w("    GCHK_SLOT")
    w("} golden_check_kind;")
    w("")
    w("typedef struct {")
    w("    golden_op_kind op;")
    w("    uint8_t addr[20];")
    w("    uint8_t token[20];")
    w("    int width;")
    w("    uint16_t id;")
    w("    uint64_t nonce;")
    w("    uint8_t value[32];")
    w("    int force;")
    w("    int expect; /* acctdrv_err */")
    w("} golden_op;")
    w("")
    w("typedef struct {")
    w("    golden_check_kind check;")
    w("    int sparse; /* table: 0 accounts, 1 sparse */")
    w("    uint8_t addr[20];")
    w("    uint16_t id;")
    w("    uint64_t index;")
    w("    int found;")
    w("    uint64_t nonce;")
    w("    uint8_t value[32];")
    w("    uint64_t count;")
    w("    const uint8_t *slot_bytes;")
    w("    size_t slot_len;")
    w("} golden_check;")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    uint64_t drive_length, capacity, load_limit;")
    w("    uint8_t seed[32];")
    w("    uint32_t profile, slot_size;")
    w("    uint64_t table_offset, registry_offset, registry_capacity;")
    w("    uint64_t sparse_offset, sparse_capacity, sparse_load_limit;")
    w("    uint32_t sparse_slot_size;")
    w("    const golden_op *ops;")
    w("    size_t nops;")
    w("    const golden_check *checks;")
    w("    size_t nchecks;")
    w("    uint8_t sha256[32];")
    w("} golden_scenario;")
    w("")

    for si, sc in enumerate(scenarios):
        checks = sc.get("checks", [])
        for ci, chk in enumerate(checks):
            if chk["check"] == "slot":
                b = bytes.fromhex(chk["hex"])
                w(
                    f"static const uint8_t g{si}_chk{ci}_slot[{len(b)}] = "
                    f"{carr(b)};"
                )
        ops = sc.get("ops", [])
        w(f"static const golden_op g{si}_ops[] = {{")
        for op in ops:
            addr = hexbytes(op.get("addr", ""), 20, "op addr")
            token = hexbytes(op.get("token", ""), 20, "op token")
            value = hexbytes(op.get("value", ""), 32, "op value")
            force = 1 if op.get("force") else 0
            w(
                f"    {{ {OPS[op['op']]}, {carr(addr)}, {carr(token)}, "
                f"{op.get('width', 0)}, {op.get('id', 0)}, "
                f"{op.get('nonce', 0)}ull, {carr(value)}, {force}, "
                f"{EXPECT[op['expect']]} }},"
            )
        w("};")
        w(f"static const golden_check g{si}_checks[] = {{")
        for ci, chk in enumerate(checks):
            addr = hexbytes(chk.get("addr", ""), 20, "check addr")
            value = hexbytes(chk.get("value", ""), 32, "check value")
            sparse = 1 if chk.get("table") == "sparse" else 0
            found = 1 if chk.get("found") else 0
            if chk["check"] == "slot":
                ptr = f"g{si}_chk{ci}_slot"
                plen = len(bytes.fromhex(chk["hex"]))
            else:
                ptr, plen = "0", 0
            w(
                f"    {{ {CHECKS[chk['check']]}, {sparse}, {carr(addr)}, "
                f"{chk.get('id', 0)}, {chk.get('index', 0)}ull, {found}, "
                f"{chk.get('nonce', 0)}ull, {carr(value)}, "
                f"{chk.get('count', 0)}ull, {ptr}, {plen} }},"
            )
        w("};")
        w("")

    w(f"#define GOLDEN_NUM_SCENARIOS {len(scenarios)}")
    max_len = max(sc["config"].get("driveLength", 0) for sc in scenarios)
    w(f"#define GOLDEN_MAX_DRIVE_LENGTH {max_len}u")
    w("")
    w("static const golden_scenario golden_scenarios[GOLDEN_NUM_SCENARIOS]"
      " = {")
    for si, sc in enumerate(scenarios):
        cfg = sc["config"]
        seed = hexbytes(cfg.get("seed", ""), 32, "seed")
        sha = hexbytes(sc["sha256"], 32, "sha256")
        w(
            f'    {{ "{sc["name"]}", {cfg.get("driveLength", 0)}ull, '
            f"{cfg.get('capacity', 0)}ull, {cfg.get('loadLimit', 0)}ull, "
            f"{carr(seed)}, {cfg.get('profile', 0)}u, "
            f"{cfg.get('slotSize', 0)}u, {cfg.get('tableOffset', 0)}ull, "
            f"{cfg.get('registryOffset', 0)}ull, "
            f"{cfg.get('registryCapacity', 0)}ull, "
            f"{cfg.get('sparseOffset', 0)}ull, "
            f"{cfg.get('sparseCapacity', 0)}ull, "
            f"{cfg.get('sparseLoadLimit', 0)}ull, "
            f"{cfg.get('sparseSlotSize', 0)}u, "
            f"g{si}_ops, {len(sc.get('ops', []))}, "
            f"g{si}_checks, {len(sc.get('checks', []))}, {carr(sha)} }},"
        )
    w("};")
    w("")
    w("#endif /* GOLDEN_VECTORS_H */")
    w("")

    with open(sys.argv[2], "w") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main()
